/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'BaseDate.picker': typeof import('./components/base-date-picker/base-date.picker.vue')['default']
    BaseDateCalendar: typeof import('./components/base-date-picker/base-date-calendar.vue')['default']
    BaseScroll: typeof import('./components/base-scroll/base-scroll.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    MyInfo: typeof import('./components/my-info/my-info.vue')['default']
    MyInfoTimeline: typeof import('./components/my-info/my-info-timeline.vue')['default']
    NavBar: typeof import('./components/nav-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingTheme: typeof import('./components/setting-theme.vue')['default']
  }
}
